<?php
/**
 * includes/crypto.php
 * AES-256-GCM authenticated encryption helpers.
 *
 * Uses the ENCRYPTION_KEY constant (32 raw bytes, hex-encoded) from
 * /config/keys.php which is auto-generated by config.php on first run.
 *
 * Format: base64( iv[12] | tag[16] | ciphertext )
 * The 'enc:' prefix is added/checked by encrypt_setting/decrypt_setting
 * to distinguish encrypted values from legacy plaintext in the DB.
 */

/**
 * Encrypt a plaintext string with AES-256-GCM.
 *
 * @throws RuntimeException on OpenSSL failure.
 */
function encrypt(string $plain): string
{
    if (!defined('ENCRYPTION_KEY') || strlen(ENCRYPTION_KEY) !== 64) {
        throw new RuntimeException('ENCRYPTION_KEY not configured or wrong length.');
    }
    $key = hex2bin(ENCRYPTION_KEY);
    $iv  = random_bytes(12);           // 96-bit nonce (GCM recommended)
    $tag = '';
    $cipher = openssl_encrypt($plain, 'aes-256-gcm', $key, OPENSSL_RAW_DATA, $iv, $tag, '', 16);
    if ($cipher === false) {
        throw new RuntimeException('Encryption failed.');
    }
    // Pack iv + authentication tag + ciphertext, then base64-encode for storage.
    return base64_encode($iv . $tag . $cipher);
}

/**
 * Decrypt a ciphertext produced by encrypt().
 *
 * @throws RuntimeException on authentication failure or format error.
 */
function decrypt(string $encoded): string
{
    if (!defined('ENCRYPTION_KEY') || strlen(ENCRYPTION_KEY) !== 64) {
        throw new RuntimeException('ENCRYPTION_KEY not configured or wrong length.');
    }
    $key  = hex2bin(ENCRYPTION_KEY);
    $data = base64_decode($encoded, true);
    if ($data === false || strlen($data) < 29) {
        throw new RuntimeException('Invalid ciphertext format.');
    }
    $iv      = substr($data, 0, 12);
    $tag     = substr($data, 12, 16);
    $payload = substr($data, 28);
    $plain   = openssl_decrypt($payload, 'aes-256-gcm', $key, OPENSSL_RAW_DATA, $iv, $tag);
    if ($plain === false) {
        throw new RuntimeException('Decryption failed: authentication tag mismatch.');
    }
    return $plain;
}

/**
 * Wrap a plaintext value for storage in the settings table.
 * Prefixes with 'enc:' so decrypt_setting() can detect encrypted values.
 */
function encrypt_setting(string $plain): string
{
    if ($plain === '') {
        return '';
    }
    return 'enc:' . encrypt($plain);
}

/**
 * Retrieve a plaintext value from a (possibly encrypted) settings value.
 * Falls back gracefully for legacy plaintext values already in the DB.
 */
function decrypt_setting(string $stored): string
{
    if ($stored === '') {
        return '';
    }
    if (str_starts_with($stored, 'enc:')) {
        try {
            return decrypt(substr($stored, 4));
        } catch (RuntimeException $e) {
            error_log('[SVMS/crypto] decrypt_setting failed: ' . $e->getMessage());
            return ''; // Fail safe — never return garbage or exception to caller
        }
    }
    // Legacy plaintext stored before encryption was added.
    return $stored;
}
